name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore .\XmegaAudio.sln

      - name: Build
        run: dotnet build .\XmegaAudio.sln -c Release --no-restore

      - name: Publish App
        run: dotnet publish .\XmegaAudio.csproj -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o .\artifacts\XmegaAudio-win-x64

      - name: Zip
        shell: pwsh
        run: |
          Compress-Archive -Path ".\artifacts\XmegaAudio-win-x64\*" -DestinationPath ".\artifacts\XmegaAudio-win-x64.zip" -Force

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/XmegaAudio-win-x64.zip

